services:
  init:
    image: alpine
    volumes:
      - ./php:/from:ro
      - php-code:/to
    command: sh -c "cp -r /from/* /to/ && chmod -R 755 /to && chown -R 33:33 /to"
    depends_on: []
  php_fpm:
    build: .
    user: "33:33"
    volumes:
      - php-code:/var/www/html
    networks: [appnet]

  php_cli:
    build:
      context: .
      dockerfile: Dockerfile.cli
    volumes:
      - php-code:/var/www/html
    networks: [appnet]

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    entrypoint: ["nginx", "-g", "daemon off;"]
    volumes:
      - php-code:/var/www/html:ro
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health.php"]
      interval: 10s
      timeout: 3s
      retries: 3
    depends_on:
      - php_fpm
      - php_cli
    networks: [appnet]

networks:
  appnet:

volumes:
  php-code:
